config/terraform/aws/cloudwatch.tf

Adds CloudWatch alarms for the following thresholds:
- CPU > 50% utilization over 2 periods of 120 seconds
- Memory > 50% utilization over 2 periods of 120 seconds

Add some CloudWatch alarms

---

FORK.md
pkg/persistence/db.go
pkg/persistence/queries.go
pkg/server/keyclaim.go
test/new_key_claim_hash_id_test.rb

This is a follow up on some of the code review comments in regards to #50.

Code review fixes

---

config/terraform/aws/cloudwatch.tf
config/terraform/aws/kms.tf

Terraform file to create KMS store with default configuration and utilize the KMS key to encrypt Cloudwatch closes #62

KMS implemented for CloudWatch log group

---

config/terraform/aws/ecs.tf
config/terraform/aws/variables.auto.tfvars
config/terraform/aws/variables.tf

ECS autoscaling with default options Closes #79

Applied default variables for autoscaling ECS

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md

Grand merci à @EliseKa pour ses révisions!

Updated translations

---

pkg/persistence/db.go
pkg/persistence/queries.go
pkg/telemetry/stats.go

Closes #103. This PR will allow us to track unclaimed key totals over time.

Adds unclaimed one time code metric

---

.github/workflows/terraform.yml
config/terraform/aws/provider.tf

The terraform github provider was updated and broke things:
https://github.com/terraform-providers/terraform-provider-github

Update github provider syntax

---

config.yaml
pkg/config/config.go
pkg/server/keyclaim.go

closes #33 
Right now, CORS header is hardcoded. Made changes to read the value from config file.

reading CORS values from configuration file

---

config/terraform/aws/networking.tf

Created the same amount of static IPs and NAT gateways as there are subnets (3), we could make this dynamic in the future with a count variable if needed
Closes #78

Changed to incorporate 3 NAT gateways in each AZ

---

config/terraform/aws/sns.tf

Closes #119 by using the custom encryption key in SNS topics.

BVC-64 :: Add encryption to SNS

---

config/terraform/aws/waf.tf

add `/services/*` and `/exposure-configuration/*` paths to WAF

Waf add paths

---

config/terraform/aws/networking.tf

- add privatelink endpoints for private access for required AWS services
- ECR API endpoints are only supports in 2 zones in the Canada region as opposed to all 3 for the other API endpoints
- this should be a noop and connections to these endpoints should now use the private endpoints allowing to us to test removing all egress access

add privatelink endpoints for AWS services

---

pkg/persistence/queries.go
pkg/timemath/timemath.go

Removes the post dating functionality as we are now only download keys every 24 hours.

Remove post dating

---

.github/workflows/build-deploy-staging.yml

fix github action `build-deploy-staging`

remove extraneous env entry

---

.github/workflows/build-push-containers.yml

prod aws login was overriding the staging aws login

Fix ecr staging

---

pkg/persistence/db.go
pkg/persistence/queries.go
pkg/server/config.go
pkg/server/retrieve.go

This PR removes the following TODO issues:
```
// TODO: serve this from somewhere else
```
Linked in https://github.com/cds-snc/covid-shield-server/issues/195
```
// TODO: adjust these to deployment and source them from env
```
Linked in https://github.com/cds-snc/covid-shield-server/issues/193
```
// TODO: this might be the right place to pad inappropriately small batches
```
Linked in https://github.com/cds-snc/covid-shield-server/issues/194
and the following suggestion:
```
// TODO: Maybe implement multi-pack linked-list scheme depending on what we hear back from G/A
```

Remove TODOs from Code base

---

config/terraform/aws/cloudwatch.tf

Sets a 365 day log retention on the cloud watch logs.

Set log retention

---

config/terraform/aws/cloudwatch.tf

This PR adds alerts for:
- Route53 DDoS alerting
- CloudFront DDoS alerting
- Alerting for Route53 health checks

Add more DDoS alerts and Route53 alerts

---

config/terraform/aws/cloudwatch.tf
config/terraform/aws/metrics.tf

Stats should use the maximum count vs the total count.
Also fixes the Route53 Health check.

Changes stats from "Total" to "Maximum"

---

config/terraform/aws/rds.tf

~Increase database retention to 15 days~
Decreases database retention to one day based on privacy policy

Decrease database retention to one day

---

.github/workflows/deploy-containers.yml

Wait for terraform apply to complete before deploying apps

deploy apps after terraform apply

---

.github/workflows/deploy-containers.yml

Github action workflow step id's must be unique.

fix wait-for-terraform id

---

config/terraform/aws/cloudwatch.tf

Sets a 90 day log retention for application logs.

90 day application log retention

---

config/terraform/aws/waf.tf

This PR changes the AWS managed rules inside the web application firewall from count to block.

Change AWS managed rules from count to block

---

config/terraform/aws/waf.tf

Just removing COUNT rules lead to an error in terraform deploy.

Set explicit block rules on WAF

---

config/terraform/aws/codedeploy.tf
config/terraform/aws/iam.tf
config/terraform/aws/lb.tf
config/terraform/aws/modules/codedeploy/main.tf
config/terraform/aws/modules/codedeploy/variables.tf

- add test listeners to the existing load balancers
- add lambda IAM role with permissions to update CodeDeploy deployments

add test listeners and lambda IAM permissions for testing deploys

---

pkg/server/config.go

For discussion - fine tuning exposure configuration based on iOS recommendations.

Tuning exposure configuration

---

config/terraform/aws/ecs.tf
config/terraform/aws/task-definitions/covidshield_key_retrieval.json
config/terraform/aws/task-definitions/covidshield_key_submission.json

Edits https://github.com/cds-snc/covid-alert-server/pull/236 because we did not put the ENV in the proper place

Rollback ENV change

---

config/terraform/aws/task-definitions/covidshield_key_retrieval.json
config/terraform/aws/task-definitions/covidshield_key_submission.json

Properly fix env

---

pkg/server/config.go

Adding additional values for attenuation duration to configuration.

Add attenuation duration to configuration

---

pkg/server/config.go
pkg/server/services.go
pkg/server/services_test.go

Refactor of #241.
Changing the endpoint from `/exposure-configuration/present` to `/services/present`
Full description here: https://github.com/cds-snc/covid-alert-app/issues/1003

Local presence

---

pkg/server/config.go

Adds the minimumExposureDurationMinutes to the config and sets a value of 15 for bucket logic.

Add minimumExposureDurationMinutes to config

---

pkg/server/services.go

Removes the urandom sampling that was added.

Remove urandom sampling

---

.github/PULL_REQUEST_TEMPLATE.md

Do you prefer having a pr template?

[Github] Add pull request template

---

.github/workflows/build-push-containers.yml

- Add an action that will generate a changelog based on commits following the conventional commit format on merge to master. 
- Tag with a bumped version based on the commit messages.
- Tag containers with git tag and deploy to registries

Generate Changelogs and Bump Version on merge to master

---

.github/workflows/build-push-containers.yml

Temporarily removes CI that we have issues with.

chore: removing ci for now

---

.gitignore

chore: Ignore goland folder

---

.github/workflows/s3-backup.yml

Adds a cron job to back up the current master branch to an S3 bucket that runs at 6 AM UTC

chore: S3 backups

---

bin/README.md
bin/add-vpn-nsg.sh
bin/daily-reports.sh
bin/docker-aws-login.sh
bin/get-sg-ids.sh
bin/remove-vpn-nsg.sh

Logs into the ECR registry in ca-central-1 region
Used to get the security group names we need
Add the VPN_SG security group to the covidshield-database security group
Run the sql that we currently use to generate daily reports
**Please note: This requires a login-path to be setup and using the same name as the aws credential you are using**
Removes the VPN_SG security group from the covidshield-database security group

toil: Some scripts I've been meaning to commit

---

bin/invalidate-cache.sh

chore: script for invalidating cache

---

bin/daily-reports.sh

Adds some better titles and a new report on unused OTK's by source

chore: update daily report script

---

.github/workflows/codeql-analysis.yml

<needs review> draft file from github, with change to cron to run daily.
Fixes:

Integrate github's new code scanning capability

---

pkg/persistence/metric_queries.go
pkg/persistence/migrator.go

Fixes:
Fixes the following issues: 
- aggregating of all OTK's that were older then 15 minutes instead of 1440 minutes for OTKUnclaimed
- aggregating all unclaimed OTK's older then 1440 minutes instead of 15 days for OTKExpired

fix: fixing deletion count issue

---

pkg/persistence/queries_test.go
pkg/server/upload_test.go

fix lint + typo

---

bin/clear-diagnosis-keys.sh
bin/daily-reports.sh

Script for clearing out diagnosis keys in a db
New script for daily reporting

chore: automating some toil

---

.github/workflows/shellcheck.yml
bin/run-shellcheck.sh
scripts/heroku_run.sh

Add a run-shellcheck.sh script in the ./bin folder
Block merge to main branch if scripts don't pass shellcheck
Closes #358

ci(scripts): add ci checks for shell scripts

---

.github/workflows/sync-labels.yml
labels.yml

fix: use env instead of with

---

labels.yml

chore: testing label change

---

.github/workflows/sync-labels.yml

ci: install github-label-sync

---

labels.yml

chore: revert label test

---

.github/workflows/build-push-monolith.yml

Set the docker registry to login to

fix: loging to the correct repo

---

.githooks/commit-msg
.github/workflows/commit-lint.yml
Makefile
bin/create-release.sh
bin/init-repo.sh
commitlint.config.js
package-lock.json
package.json

Adds a make init to initiatlize the repository that does the following:
- Installs npm tools
- Copys over githooks
Adds a new workflow to lint commit messages

release: lint commit messages to ensure they adhere to Conventional Commit 

---

Makefile

fix: move init to end of file

---

.dockerignore
Dockerfile

Upgrade the golang version to the latest version
Convert the .dockerignore to be a safelist instead of a blocklist

feat: update dockerfile

---

.github/workflows/deploy-containers.yml

Adds the matrix keyword to properly reference the matrix variable APPSPEC_FILE

fix: add matrix to APPSPEC_FILE

---

.github/workflows/deploy-containers.yml

We were missing a `)` in the deploy workflow, this adds that back in. 
I also went over the rest of the file line by line so 🤞🏼 this should pass.

fix: add required )

---

.github/workflows/deploy-containers.yml

fix(ci): update amazon-ecs-deploy-task-defintion to v1.4.2
