.github/workflows/snyk.yml, .github/workflows/terraform.yml
When we first provisioned the server environment, the Terraform GitHub action still pulled the latest available version of Terraform, in this case, 0.13. 
A recent update to the GitHub action, this was changed to the latest stable version: 
https://github.com/hashicorp/setup-terraform/issues/23#issuecomment-646621002
However, our current state was set with 0.13 which means the current action fails:
https://github.com/cds-snc/covid-shield-server/runs/788565440
This update to our action flow pins the Terraform version to 0.13.
=> Pin TF version

.github/workflows/terraform.yml
Terraform was no longer initializing properly because of the upstream change.
=> Init properly

.devcontainer/docker-compose.yml, cmd/key-retrieval/main.go, cmd/key-submission/main.go, cmd/monolith/main.go, pkg/app/app.go, pkg/persistence/db.go, pkg/persistence/queries.go, pkg/telemetry/stats.go, pkg/telemetry/telemetry.go
The purpose of the feature is to add additional metrics to the current metrics output that show how many claimed one time codes are in the database (claimed keys) and how many diagnostic keys have been uploaded. Based on this data, we should be able to create alerts on unusual behaviour. Here is an example output:
```
{
"time":"2020-06-21T00:23:07.4527958Z",
"updates":[
{
"name":"covidshield.system.memory.total",
"min":4131897344,
"max":4131897344,
"sum":4131897344,
"count":1
},
...
{
"name":"covidshield.app.claimed_keys.total",
"min":4,
"max":4,
"sum":4,
"count":1
},
{
"name":"covidshield.app.diagnosis_keys.total",
"min":56,
"max":56,
"sum":56,
"count":1
}
]
}
```
=> Added Key stats from database to metrics

pkg/persistence/db.go, pkg/persistence/migrator.go, pkg/persistence/queries.go, pkg/server/keyclaim.go, test/lib/helper.rb, test/new_key_claim_hash_id_test.rb, test/new_key_claim_test.rb
There is a scenario where a healthcare provider might like to allow people to issue their own claim codes through a self-serve interface. In this case the user can abuse the system to generate claim codes and sharing those with others, who then use their devices to flood the system with data.
One way to mitigate this is that the self-serve interface attaches a unique 128 character code to the one time token generation url, `/new-key-claim/{hashId:[0-9,a-z]{128}}`. If the same URL is called again and, it checks if the `hashId` exists, and if does and has been claimed, returns a 401. If it does not exist, returns a 200 with a new code. 
The hashId check comes after the Bearer authorization check.
As this is just another URL pattern match, it does not impact users who want use the existing …
=> Add HashId logic

.github/workflows/ecr-prod.yml
This pull request adds a GitHub action that will push the current image into the docker registry used for the production deploys.
=> Adding ECR Prod as a registry target

FORK.md, config/terraform/aws/networking.tf
Closes #70. The inherited Terraform included an egress to connect to the healthcare portal component. This component is currently out of scope so the egress port can be removed.
=> Removed portal security group

config/terraform/aws/cloudfront.tf
Closes #68 and closes #69 
Restricts the methods that can access the Cloudfront distribution to GET and HEAD, which are the two methods that are compressed. Should the retrieval server ever need other methods opened up, we can adjust it later. 
Also enabled compression for Cloudfront.
=> Small changes to Cloudfront settings

config/terraform/aws/vpc_flow_log.tf
Closes #63. This pull request enables flow logging on the main CovidShield VPC and put the logs into an encrypted Cloudwatch log
=> Add VPC flow logging

config/terraform/aws/ecs.tf, config/terraform/aws/kms.tf
Fixes key policy so it can be used to encrypt KMS logs: https://github.com/terraform-providers/terraform-provider-aws/issues/8042#issuecomment-482315478
=> Add policy to KMS

config/terraform/aws/cloudwatch.tf, config/terraform/aws/vpc_flow_log.tf
Uses the KMS key ARN vs ID, although the value in CloudWatch TF object is ID.
=> Set key ARN

FORK.md, config/terraform/aws/bootstrap/provider.tf, config/terraform/aws/bootstrap/variables.tf
Closes #59, closes #81, closes #73, and closes #82 which are all concerned with how the initial infrastructure is provisioned to manage the terraform state. 
The bootstrap terraform included in this PR should be run before the main terraform is run. It will:
- Create a new and securely encrypted S3 bucket 
- Provision a DynamoDB table to handle state locks
- Provision the Route53 zone that the main application will live in.
It is important to note that once this terraform is run, the Route 53 zone has to be manually imported into the terraform state for the main application. 
ex: `terraform import aws_route53_zone.covidshield XXXXYYYYZZZZ` 
More information can be found here: https://www.terraform.io/docs/providers/aws/r/route53_zone.html#import
=> Adds example bootstrap configuration for Terraform

config/terraform/aws/ecs.tf
Closes #90. Unfortunately the `LATEST` version of Fargate defaults to 1.3. We would like to use 1.4 features.
=> Set Fargate platform to 1.4.0

config/terraform/aws/variables.auto.tfvars
The r5 series is the next generation version of the r4 database line.
=> Switch DB from r4 to r5

.devcontainer/Dockerfile, Dockerfile, pkg/persistence/db.go
Closes #64. 
Docker image are now built with the AWS cert bundle. If the DB is configured to use an `*.rds.amazonaws.com` domain, then it will configure the MySQL connection string to use the TLS connection.
=> Enable SSL connection if DB is RDS

.devcontainer/docker-compose.yml, .github/workflows/pr-test-ci.yml, dev.yml, docker-compose.yml, pkg/keyclaim/authenticator.go, test/lib/helper.rb, test/new_key_claim_hash_id_test.rb, test/new_key_claim_test.rb, test/upload_test.rb
Closes #113. 
Enforced a minimum length of 20 character for each `KEY_CLAIM_TOKEN`
=> BVC-48 :: Enfore minimum length on KEY_CLAIM_TOKEN

pkg/server/keyclaim.go
Closes #116 
Assuming:
The default forwarded request from ALB to backend X-Forwarded-For HTTP header is as below:
`X-Forwarded-For: $sourceIP`
Therefore, any application/service processing HTTP request X-Forwarded-For HTTP header will pick $sourceIP in the case above.
In the case where a client sends a custom http request with a fake IP 1.1.1.1 included in the X-Forwarded-For HTTP header the ALB forwards the request to the back end as below:
` X-Forwarded-For: 1.1.1.1,$sourceIP`
Therefore, any application/service processing HTTP request X-Forwarded-For HTTP header should always pick the last appended IP which is the $sourceIP in the case above.
The code only needs to select the last IP from a comma separated list.
=> BVC 52 :: Extract last appended IP from X-Forwarded-For header

pkg/persistence/db.go, pkg/persistence/queries.go, pkg/server/upload.go, test/lib/helper.rb, test/upload_test.rb
Fixes #111
Extracts `remaining_keys` on initial query. If `keys_inserted` is larger than `remaining_keys` rolls back transaction.
=> BVC-41 :: Fixes faulty bounds checking for keysRemaining in key upload

pkg/server/keyclaim.go
Part of #117.  Fixes a bug in the IP reader from the ALB. We assumed it would send IPs in this format `x,y,z` when in fact it sends them in `x, y, z`.
=> Trims last IP passed from ALB

config/terraform/aws/waf.tf
- convert legacy waf rules to wafv2 with latest AWS provider
- add `AWSManagedRulesAmazonIpReputationList`, `AWSManagedRulesCommonRuleSet`, `AWSManagedRulesKnownBadInputsRuleSet`, `AWSManagedRulesLinuxRuleSet`, and `AWSManagedRulesSQLiRuleSet` AWS managed rulesets
- enabled cloudwatch metrics per rule
- enable sampling for each rule except for the explicit ALLOW rule
- enabled rate limiting for `/claim-key`, `/new-key-claim*`, and `/upload`
TODO:
=> convert legacy waf to wafv2 and add managed rules

config/terraform/aws/waf.tf
Let's leave the WAF rules in permissive mode for a few days to confirm we're not going to cause issues.
=> switch waf to fail open and count blocks

config/terraform/aws/waf.tf
With default action of allow, none of the count rules get any hits. 
Fixes https://github.com/cds-snc/covid-shield-server/pull/126
=> waf needs to block by default otherwise it won't count hits

pkg/server/config.go
For now we should set the simplest configuration possible that conforms to HC guidance (<=2m, >=15 minutes). We assume longer exposures are not higher risk for now.
The weights are unused and reserved for future use.
@jeberhardt feel free to comment with some more details about how we arrived at this configuration.
=> Update EN framework configuration

config/terraform/aws/shield.tf
NOTE: AWS Shield must be manually enabled via WebUI or CLI for each account.
=> enable AWS Shield DDoS protection on ALB, CDN, and DNS

config/terraform/aws/ecs.tf, config/terraform/aws/provider.tf
The github provider is no longer required as the `github_sha` variable is always declared.
=> remove github provider

config/terraform/aws/lb.tf
ALB's unfortunately do not support custom cipher suite policies but `ELBSecurityPolicy-FS-1-2-Res-2019-08` is the most restrictive one and supports targeted mobile OS versions.
=> use a more restricted TLS cipher suite security policy

config.yaml, pkg/config/config.go, pkg/server/retrieve.go, test/lib/helper.rb, test/retrieve_test.rb
To aid rapid testing we are adding a feature flag that disables the check if you are downloading a key for the current day. 
Currently, out of privacy reason, we do not allow people to download keys that were uploaded on the current date. Usually there are no keys for the current date because the mobile app can not retrieve them from the framework unless it is running in debug mode. As a result this is another safeguard, but to aid testing we will disable it in staging.
=> Add feature flag for current date check feature

Dockerfile.heroku, app.json, heroku.yml, scripts/heroku_run.sh, test/app.json
This pull request adds Heroku PR review apps to the repository. (https://devcenter.heroku.com/articles/github-integration-review-apps)
This allows us to test against builds based on the PR code that are hosted in the cloud vs. on developer machines. The review apps make use of the `monolith` build which includes both the `submission` and `retrieval` endpoints. It also uses a SAAS DB cloud provider called JawsDB. JawsDB provides an environment variable with the connection string. As Go requires a specific connection string format, we munge the environment variable into the correct format with a script before we boot the server.
The environment variables for the app itself are the same as for the docker-compose, or local dev, environments.
=> Adds Heroku PR Review apps

pkg/persistence/queries.go
Closes #140. Using `FOR UPDATE` should prevent other attempts from creating a transaction based on this `SELECT` query.
=> Locks row for key registration

pkg/retrieval/retrieval.go, pkg/retrieval/signer.go, test/retrieve_test.rb
Based on observations that the underlying frameworks are rejecting the signatures of ZIP file I have made the following changes:
1. Changed the signing functionality from X962 signature to the implementation found on the Google reference server
https://github.com/google/exposure-notifications-server/blob/1208580e92e3a9f23d85eb570fbdff8d1f6e7a00/internal/export/exportfile.go#L217-L224
2. Included the header payload as part of the signed payload - another pointer from the the Google reference server
https://github.com/google/exposure-notifications-server/blob/1208580e92e3a9f23d85eb570fbdff8d1f6e7a00/internal/export/exportfile.go#L178
3. Adjusted the Ruby tests, which now verify the signature. 
I validated the signature using this tool: …
=> Signature fixes

pkg/persistence/queries.go
Previous to this bug if you tried to submit keys to a one time code that had reached a 0 upload key remaining, you could leave the transaction open, locking the database.
=> Fix a bug where a transaction was not closed

config/terraform/aws/ecs.tf, config/terraform/aws/networking.tf, config/terraform/aws/outputs.tf
Currently Covidshield has no requirements for egress connectivity and therefore egress access should be removed.
- remove `covidshield_egress_anywhere` security group
- remove NAT Gateways and corresponding routes
- switch VPC endpoints to use private subnets where fargate tasks are
- add explicit egress SG rules from tasks to VPC endpoints and RDS instance
=> remove all resources for egress network connectivity

config/terraform/aws/kms.tf
Currently alarms are not sending messages to the SNS topics because they can't access the default KMS key. Solution is referenced here: https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-receive-sns-for-alarm-trigger/
=> Add permissions for Alerts to send to SNS topics

pkg/server/keyclaim.go, test/new_key_claim_hash_id_test.rb, test/new_key_claim_test.rb
closes #98 
This pull request is to make the error codes/error messages generic for  "/new-key-claim" endpoint that generates the 8 digit code.
=> updated the error codes for /new-key-claim endpoint that generates the 8 digit code

config/terraform/aws/networking.tf
subnet id's in the nacl keep showing up in the TF plan due to https://www.terraform.io/docs/providers/aws/r/default_network_acl.html#managing-subnets-in-the-default-network-acl
=> ignore subnet id's in nacl

config.yaml, pkg/proto/covidshield/defs.go, pkg/server/upload.go, pkg/timemath/timemath.go, test/upload_test.rb
This PR allows keys to have a `rollingPeriod` less than 144. The use case for this may be when users would like to upload todays key, in which case the framework will provide two keys for that day with the same `rollingStartIntervalNumber`. ex:
```
{
keyData: 'ATtHjF3BQbJhcQprMWjTkg==',
rollingPeriod: 104,
rollingStartIntervalNumber: 2656800,
transmissionRiskLevel: 0,
},
{
keyData: 'IBjwbMPl7526ljC3DcBEGQ==',
rollingPeriod: 142,
rollingStartIntervalNumber: 2656800,
transmissionRiskLevel: 0,
}
```
This requires the following changes:
- Increasing the maximum number of keys uploaded per one time code to 43. (On day 0 you upload 14 keys for the previous  days, and one key for half of day 0, plus 28 keys for the consecutive 14 days - assuming you upload once a day for the next 14 days, in …
=> Variable rolling period

pkg/persistence/db.go, pkg/persistence/queries.go, pkg/server/keyclaim.go, test/new_key_claim_hash_id_test.rb
Closes #147. 
This PR changes the HashID logic by incorporating all the required queries into a single transaction with a "FOR UPDATE" lock. This removes the race condition where by two one time codes could have the same HashIDs.
=> BVC-71 :: TOUTOC bug in new-key-claim endpoint

config/terraform/aws/ecs.tf
`aws_ecs_service` resource requires a task definition intially.
=> add taskdef back to ecs service

.github/workflows/build-push-containers.yml
- aws-actions/amazon-ecr-login doesn't seem to support multiple ECR registries from different accounts
=> fix ecr logins

config/terraform/aws/codedeploy.tf, config/terraform/aws/modules/codedeploy/main.tf, config/terraform/aws/modules/codedeploy/variables.tf, config/terraform/aws/variables.tf
Allow the termination_wait_time_in_minutes to be overridden by env var and set default to 1min
=> default old deploy termination to 1 and allow overriding via env var

config.yaml, pkg/config/config.go, pkg/server/retrieve.go, test/retrieve_test.rb
This is a feature that will allow a person to download all the key for the period defined by `numberOfDaysToServe`, currently 14, in one package.
The access the feature,` enableEntirePeriodBundle ` needs to be set to `true`. 
Instead of the regular day number since unix time, ex: `18440` we use `00000` because that is not a valid date but does not require the creation of a new API endpoint or changing the authorization logic behind retrieving bundles. The mobile client can use that as a default before replacing it with the current day.
=> Add download entire period bundle feature

config/terraform/aws/metrics.tf
Adds additional application based log metrics.
Why do we have a count of 8 AWS metrics per metric you ask?
App metrics are logged as an array in JSON ex:
```
{
"time": "2020-07-09T22:06:18.913005245Z",
"updates": [
{
"name": "covidshield.system.memory.free",
"min": 16060346368,
"max": 16060346368,
"sum": 16060346368,
"count": 1
},
{
"name": "covidshield.system.cpu.percent",
"min": 0.5494505494505346,
"max": 0.5494505494505346,
"sum": 0.5494505494505346,
"count": 1
},
{
"name": "covidshield.app.claimed_one_time_codes.total",
"min": 403,
"max": 403,
"sum": 403,
"count": 1
}
...
}
```
The problem is that this array has 8 items and AWS Cloudwatch can't filter on a variable position. ex: `{$.updates[*].name = ...` The order of the array is also always different, so we need a metric filter for …
=> Add app based log metrics

pkg/persistence/db.go, pkg/persistence/queries.go, pkg/server/retrieve.go, test/retrieve_test.rb
Fixes logic in #176. When I implemented the logic I relied on the Ruby test to pass. Unfortunately the Ruby logic never called an assert. I have fixed the test and simplified the logic so you can pass it startHour and endHour need to be explicitly set before it gets passed to the query function.
=> Convert day bounds to hour bounds

.github/workflows/terraform.yml, config/terraform/aws/variables.tf, config/terraform/aws/waf.tf
ref: #99 
- allows a list of CIDR ranges to be allowed to the `/new-key-claim` endpoint
- TF_VAR_new_key_claim_allow_list secret is required and can be set to `["0.0.0.0/1", "128.0.0.0/1"]` to allow all
=> configurable IP allow list for /new-key-claim endpoint

.github/workflows/terraform.yml, config/terraform/aws/kinesis.tf, config/terraform/aws/s3.tf, config/terraform/aws/variables.tf, config/terraform/aws/waf.tf
-requires TF_VAR_environment to create a unique s3 bucket
- enables wafv2 logging, creates kinesis firehose delivery stream, and target s3 bucket
- redacts "authorization" header
=> enable wafv2 logging

.github/workflows/terraform.yml, config/terraform/aws/ecs.tf, config/terraform/aws/variables.tf
By removing the git sha tag from the task definition image reference, terraform will stop trying to change the task definition on every commit.
=> set taskdef image to repo name without sha to avoid plan changes

config/terraform/aws/cloudfront.tf
Use Cloudfront CDN Price Class 100 as per https://aws.amazon.com/cloudfront/pricing/
=> use priceclass 100 for Cloudfront CDN

config/terraform/aws/cloudfront.tf, config/terraform/aws/cloudwatch.tf, config/terraform/aws/kinesis.tf, config/terraform/aws/route53.tf, config/terraform/aws/waf.tf
- Adds alarms for when the DDoS alerts are triggered on both the submission and retrieval ALB.
- Adds additional Route53 health checks that can be used by the DDoS team
- Adds allow all WAFs for retrieval ALB and retrieval CDN to capture logs
Closes #71 and Closes #89
=> Changes for AWS Shield

.github/workflows/terraform.yml, config.yaml, config/infrastructure/aws/README.md, config/terraform/aws/cloudfront.tf, config/terraform/aws/variables.tf, config/terraform/aws/waf.tf, pkg/config/config.go, test/claim_key_test.rb, test/new_key_claim_hash_id_test.rb
- add 5 rate limit rules of 100 requests / ip / 5min to submission endpoint
- add 1000 requests / ip / 5min rate limit rule to retrieval cloudfront distribution
- add a shared custom header between cloudfront and retrieval ALB endpoint so that requests can only come from cloudfront
- update README for new TF_VAR env vars
closes: #200
=> add more rate limit WAF rules and custom header for cloudfront

config.yaml, pkg/config/config.go, pkg/persistence/db.go, pkg/persistence/migrator.go, pkg/server/keyclaim.go, scripts/create-upload-payload-for-load-testing, test/claim_key_test.rb, test/lib/helper.rb, test/new_key_claim_hash_id_test.rb, test/new_key_claim_test.rb
This pull request extends the one time code key space from 8 numeric digits to a 10 alphanumeric key space with 22 characters. The format of the new code is three groups (A,B, and C) in the following format: AAABBBCCCC. Each group an either container letters or numbers, but not both. Example codes are:
```
296JYYQRWE
669YES8644
ZLE9859958
446657ZWKH
628977WUYZ
EXQ699AQAW
EYH299YLER
795YHFSYLH
EAS8757467
642788EJQA
```
=> Extend One Time Code Keyspace

config/terraform/aws/cloudwatch.tf, config/terraform/aws/metrics.tf, config/terraform/aws/sns.tf
Closes #204. 
This PR adds some more alerts for metrics:
- UnauthorizedNewOneTimeCodeRequests alerts critical at 100 occurrences in 5 minutes.
- UnauthorizedOneTimeCodeClaimRequests alerts critical at 100 occurrences in 5 minutes.
- UnauthorizedUploadRequests alerts critical at 100 occurrences in 5 minutes.
- 500Response alerts critical after 10 occurrences in 1 minute.
- ErrorLogged alerts critical after 10 occurrences in 1 minute.
- UnclaimedOneTimeCodeTotal alerts warn after 250 keys found in the DB.
- UnclaimedOneTimeCodeTotal alerts critical after 400 keys found in the DB.
- ClaimedOneTimeCodeTotal alerts warn after 3000 keys found in the DB.
- ClaimedOneTimeCodeTotal alerts critical after 4500 keys found in the DB.
- DiagnosisKeyTotal alerts warn after 9000 keys found in the DB.
- …
=> Adds more alerts for metrics

config/terraform/aws/s3.tf
- blocks public access to WAF log s3 bucket
- expires WAF logs after 90 days
=> block public access and expire WAF logs after 90 days

config/terraform/aws/cloudwatch.tf
During testing we realized that the metric was "off by one"
=> Adjusts DDoS threshold alerts

config/terraform/aws/waf.tf
Follow up on #216. AWS Managed rules need an override none to act in block.
ex from WAF JSON.
```
"Rules": [
{
"Name": "AWS-AWSManagedRulesAmazonIpReputationList",
"Priority": 0,
"Statement": {
"ManagedRuleGroupStatement": {
"VendorName": "AWS",
"Name": "AWSManagedRulesAmazonIpReputationList"
}
},
"OverrideAction": {
"None": {}
},
```
=> Set override action to none

pkg/server/keyclaim.go
When the code determined a Hash ID was used, the code would log the entire header including the bearer token, this could have led to a disclosure of the Bearer tokens through logs.
=> Remove header from logging

.github/workflows/deploy-containers.yml, config/infrastructure/aws/appspec-template.json, config/terraform/aws/codedeploy.tf, config/terraform/aws/lambda/lambda_validate_deploy.rb, config/terraform/aws/networking.tf
Leverage CodeDeploy validation hooks to test new deployments before shifting production traffic to new deployment.
=> add validation on test listener before shifting prod traffic

config/terraform/aws/waf.tf
WAF incorrectly allows requests for `/exposure-configuration` on the submission endpoint.
=> remove waf statement for /exposure-configuration in submission endpoint

CONTRIBUTING.md
This PR updates some of the contributing instructions that were using the https://github.com/covidshield steps to using some appropriate for COVID Alert. I also renamed a few instances of COVID Shield in this document to reflect the new name.
=> Update contributing docs to use COVID Alert specific instructions

config/terraform/aws/kms.tf, config/terraform/aws/sns.tf
SNS topics in the US need access to a US encryption key. The SNS topics are used for Route53 and Shield alerts. The reason why we need to SNS topics in US-East is because Route53 and Shield for Cloudfront are global resources, which report their metrics into US-East.
=> Creates KMS in US-East and uses it for SNS

config/terraform/aws/ecs.tf, config/terraform/aws/modules/codedeploy/main.tf, config/terraform/aws/rds.tf, config/terraform/aws/variables.tf
app replicas won't get bumped because of ignore_changes for autoscaling. However, autoscaling is disabled from codedeploy, will fix in another PR.
=> bump db and app replicas to 3 (separate AZs)

config/terraform/aws/networking.tf
- splitting the LB egress rules by target zone allows for quicker and easier removal of a zone rule in the event of an AZ outage and the target group doesn't properly mark the AZ's target task as unhealthy.
=> split the LB egress SG rules by target zone

config/terraform/aws/cloudfront.tf, config/terraform/aws/s3.tf, config/terraform/aws/waf.tf
- enable cloudfront logging for the retrieval distribution
- bump retrieval WAF rate limit rule from 1000 to 10,000reqs/5min/IP
=> Cloudfront waf updates

config/terraform/aws/ecs.tf, config/terraform/aws/task-definitions/covidshield_key_retrieval.json, config/terraform/aws/task-definitions/covidshield_key_submission.json
This makes the already used terraform environment variable available to the app so that we can feature flag based on environments. Recommendation for #235
=> Makes ENV variable accessible to app

pkg/server/services.go
***STAGING ONLY, PLEASE DO NOT INCLUDE IN PROD RELEASES***
We would like to do some sampling on our staging endpoint. To that end I have added two endpoints that will:
- Return 1 million byte sample from `/dev/urandom`
- Return 10,000 OTC
=> STAGING ONLY: Adds temporary sampling endpoints

pkg/server/services.go
Removes the password sample endpoint as the work as been completed. This fixes the direct sampling of the `urandom` endpoint as the `head` command is not available in the scratch containers.
=> Fixes urandom in scratch containers

config/terraform/aws/cloudfront.tf, config/terraform/aws/s3.tf
Part of #195. 
This creates a new s3 bucket that will house all the content for requests going to the retrieval `/exposure-configuration/`. It also adds logging to that bucket. 
Additionally it adds the bucket to the cloudfront distribution, however, routing to the bucket is still turned off, as there is no content in the bucket. If we enable routing, the time between adding the bucket and populating it would break the endpoint.
We will add the routing once the content has been populated.
=> Part #1: set up buckets and origin

Makefile, pkg/persistence/migrator.go, pkg/proto/covidshield/defs.go, pkg/server/upload.go, pkg/timemath/timemath.go
Adds a new makefile target for formatting code and runs it on existing code. In the future we can probably add a CI step to check that `gofmt` does not result in any modifications.
=> [Makefile] Add format target

config/terraform/aws/cloudfront.tf, config/terraform/aws/s3.tf
Concludes #195 
This is a follow up on #249 where we created the CloudFront origin and the S3 bucket. We have now populated the CF bucket with the correct content.
This PR changes the CloudFront distribution to redirect traffic for the `/exposure-configuration/` path to the S3 bucket. It also adds a bucket permission so that only the CloudFront distribution can access the contents of the S3 bucket.
=> Part 2: Redirect CF traffic and set bucket permissions

.clconfig.js, .github/workflows/build-push-containers.yml, .github/workflows/deploy-containers.yml, .gitignore
- Install config using NPM so we can reference the config in`.clconfig.js`
- Add node_modules to .gitignore so it doesn't get commited when the changelog commits
- Run the changelog on empty commits so we don't break CI
- add configuration to output more commits to the changelog
- tag a new version even if no output to change log
- make deploy-containers action contingent on terraform and build
success
=> CI: Fixes the CI for conventional commits 

pkg/app/app.go, pkg/workers/expiration.go
This is a small refactor of the code that moves the expiration worker from its own `expiration` directory to a `workers` directory. This would allow us to add additional `worker` instances and keep the organized. For example we may want a stats aggregator worker that runs every sixty minutes vs the thirty seconds that the current expiration worked is running on.
We could have included each worker in their own subdirectory, however, there is some shared code we us per worker, ex the `worker` struct. It would probably make sense to share that code.
Alternative implementations.
=> refactor(workers): Refactors location of worker code to add more workers

config/terraform/aws/cloudwatch.tf, config/terraform/aws/route53.tf
Fixes: #267 
Adds Route53 health checks to the static content served up by the S3 buckets. AWS has canaries that can do this, however, they do not exist in terraform yet. The drawback of Route53 checks is that they run every 30 seconds and from multiple regions, which will increase the traffic to those endpoints. However, the tradeoff is not significant enough to remove these from Terraform.
The code limits the regions from the maximum eight to the minimum three from which health checks are run.
=> S3 bucket content checks

pkg/workers/defs.go, pkg/workers/expiration.go
refactor(workers): makes workers more modular by abstracting the base genmain functions
Extension of #272. This allows a generic definition for workers to be used so it should be easier to add additional workers. the `worker` type went from 
```
type worker struct {
db       persistence.Conn
interval time.Duration
tomb     *tomb.Tomb
}
```
to 
```
type worker struct {
name     string
db       persistence.Conn
interval time.Duration
tomb     *tomb.Tomb
runner   func(w *worker, ctx context.Context) error
}
```
The new `name` attribute is used for logging purposes because previously there was a global definition using the `expiration` namespace for logging on the worker.
The new `runner` attribute is the function that gets run when the `genmain` `Run` function is executed at the specified …
=> Add worker defs

pkg/persistence/db_test.go, pkg/persistence/queries.go, pkg/persistence/queries_test.go
Removes a log of how many keys were uploaded. We do not need this information any more and it just increases the information exposure for some of the future features we are planning.
=> feat: Remove key count logging

.devcontainer/devcontainer.json, Makefile, scripts/install_dev_tools.sh
Closes #269 
This takes care of some technical debt we had on the dev container for vscode. 
- Added `golang.go` extension to build process for dev container
- Refactored `postCreateCommand` into a script in `scripts/install-dev-tools.sh`, which installs all the go tools that are installed by the extension
Installed go tools are:
```
github.com/mdempsky/gocode
github.com/uudashr/gopkgs/v2/cmd/gopkgs
github.com/ramya-rao-a/go-outline
github.com/acroca/go-symbols
golang.org/x/tools/cmd/guru
golang.org/x/tools/cmd/gorename
github.com/cweill/gotests/...
github.com/fatih/gomodifytags
github.com/josharian/impl
github.com/davidrjenni/reftools/cmd/fillstruct
github.com/haya14busa/goplay/cmd/goplay
github.com/godoctor/godoctor
github.com/go-delve/delve/cmd/dlv
github.com/stamblerre/gocode …
```
=> chore(dev_container): fixes dev tools on dev container

.github/workflows/build-push-containers.yml
Closes #274 
Removes the monolith image that includes both the key-submission and key-retrieval server in one from the build output. We do not use the image in production, so it is not required. However, we use it for Heroku PR review apps (https://github.com/cds-snc/covid-alert-server/blob/master/Dockerfile.heroku#L28), so we should keep it around until we no longer use Heroku.
=> build: remove monolith image from build

.github/workflows/build-push-gcr.yml
Part of #287. This add as a build action that pushes a monolith to Google Container Registry, which is public unlike AWS, where a Heroku PR review app in the mobile repo can deploy it.
Tested with the action running on branches vs. on master
=> build: push monolith image to GCR

.devcontainer/docker-compose.yml, config.yaml, examples/new-key-claim/curl.sh, pkg/config/config.go, pkg/server/keyclaim.go, pkg/server/retrieve.go
Instead of getting the region code from environment variables we are
hard coding it. This is so we can replace the region code in the env
vars with a province identifier that we can use for tracking events in
the system.
I'm pretty sure this is all we need to do in code to satisfy #290 the rest will have to come from the environment variables.
=> refactor(region code): hard code the region code

pkg/server/upload.go
The protobuf definition for Upload shows timestamp as an optional field:
optional google.protobuf.Timestamp timestamp = 1;
As such, the server will demarshal Uploads that lack a timestamp.
However, the server will later dereference the timestamp to access the
seconds count, reliably panicking the server and unexpectedly breaking
the connection to the client.
The panic is caught by safely.Recover, so the harm is minimized.
Further, executing this code path requires a COVID-19 diagnosis.
Nevertheless, the behaviour is still incorrect and should be hardened.
By explicitly checking if timestamp is non-nil, the panic is fixed and
INVALID_TIMESTAMP is returned as expected.
Signed-off-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>
=> Fix nil dereference if timestamp is not specified

proto/README.md
Four are listed, not five.
Signed-off-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>
=> Fix proto documentation

proto/covidshield.proto
This was changed but the protobuf wasn't synced.
Signed-off-by: Alyssa Rosenzweig <alyssa@rosenzweig.io>
=> Update one_time_code comment in protobuf definition

pkg/app/app.go
This PR moves the events endpoint from the submission the retrieval endpoints. 
This is due to the amount of IPs that need to be safelisted on the submission server for google scripts to work. 
https://github.com/cds-snc/covid-alert-server-staging-terraform/pull/31 needs to be merged first before this works.
=> refactor: move the events endpoint

pkg/server/metrics.go, pkg/server/metrics_test.go
Add a return after we fail authorization instead of continuing
Add some more tests to cover this case and a few others
=> fix: return when access is unauthorized

cmd/key-retrieval/main.go, cmd/key-submission/main.go
Since this is only going in staging submission is the better endpoint as it's safelisting is permissive in staging but restricted in prod this will provide an extra layer of protection in case it's enabled in prod.
=> feat: switch test tools from retrieval to submission

.github/workflows/pr-test-ruby-ci.yml, .github/workflows/snyk.yml, .snyk
Add a `.snyk` file to ignore the two MPL 2.0 License issues we don't have an issue with. 
Fix snyk workflow file. 
Closes #354
=> ci: ignore license issues

.github/workflows/build-push-gcr.yml
Fixes an issue with google-github-actions/setup-gcloud using deprecated commands in github
actions
See https://github.com/google-github-actions/setup-gcloud/issues/239
Fixes #357
=> ci: upgrade google-github-actions/setup-gcloud to 0.2.0

pkg/persistence/main_test.go, pkg/persistence/migrator.go, pkg/persistence/otk_duration.go, pkg/persistence/otk_duration_test.go, pkg/persistence/queries.go
Add a new table in the database to store aggregate OTK lifetimes by day,
province and hours live.
Related to #308
=> feat: track OTK lifetimes to the hour

.github/workflows/build-push-monolith.yml
Should be all upper case with underscores between words
=> fix: use proper env variables

commit_msgs.md
A document outlining how commit messages should be structured.
=> docs(release): document commit message rules

bin/report.sh
Adds a script that looks at the success and failures on the claim-key endpoint and generates a CSV for consumption. In order to generate a report you will need to modify the script for the dates you want. This is fairly simple and can be done by anyone familiar with Bash.
=> feat: added success percent report

pkg/persistence/migrator.go
fixes #428 
This PR adds a migration that will drop the otk_life_durations table and create a new one in it's place that uses the `originator` and `hours`  as a unique key constraint on the table instead of `originator` and `duration`
As the data we previously captured is essentially worthless due to this bug and we cannot re-generate the actual metrics dropping the table and recreating it through a migration is the easiest solution to this bug. 
Make sure that migration works.
=> fix: drop old duration table replace with new one

.github/workflows/deploy-containers.yml
Fixes:
A bug where deploys to staging aren't occurring.
See the following error: https://github.com/cds-snc/covid-alert-server/actions/runs/519104768 
This PR changes all the short shas in the `deploy-containers.yml` file to the equivalent long shas. 
It also converts the two actions into a single matrixed action as they were simply copied and pasted versions of each other
The assumption is that with Github recently dropping support of pinning actions to short SHAs that the actions defaulted to a newer version of the actions that we tried to pin. Potentially this introduced a bug in the current version of the aws-actions/amazon-ecs-deploy-task-definition action.
I opted not to upgrade to newer versions of the action in order to minimize the number of changes to this PR, but will upgrade …
=> fix(ci): pin long sha on deploy actions

.github/workflows/deploy-containers.yml
Adds back in the ECR login, as it not being there caused deployments to fail.
Pins to long sha for v1 as of today.
=> fix: add ecr login

.github/workflows/build-push-monolith.yml
GitHub Actions recently started using Ubuntu 20.04 when we specify we want to use the ubuntu-latest image. The AWS CLI v2 is already installed in this new version, see actions/virtual-environments#1816
Add the --update flag to install the latest available version and override the default one GitHub gives us.
Similar to https://github.com/cds-snc/notification-admin/pull/918
=> fix: monolith CI action

pkg/persistence/migrator.go, test/qr_retrieval_test.rb, test/qr_submission_test.rb
This PR makes the severity of the and outbreak optional in that it does not check for a value on upload and defaults to `0` when the outbreak is downloaded. This way, regardless of the input on the portal end, the app will have a consistent model in evaluating the data.
=> feat: make severity optional in upload and default to 0 on download

.github/workflows/build-push-containers.yml, go.mod, go.sum
The Demo environment has been shut down so the Demo ECR no longer exists.
Closes #453
=> fix: remove Demo ECR Docker image buld and push

bin/stuff-database/requirements.txt
This fixes a [security vulnerability](https://app.snyk.io/vuln/SNYK-PYTHON-URLLIB3-1533435) that exists with `urllib3 < 1.26.5`.
This should have no impact on the server as it is only a standalone utility that is being updated.
=> chore: bump `bin/stuff-database` Python dependencies

.github/workflows/snyk.yml, pkg/app/app.go, test/expiration_worker_test.rb, test/lib/helper.rb
Move the database migration work and the expiration worker from the retrieval server to the submission server.
We are doing this so that we can have the retrieval server use the readonly end point for RDS which should reduce DB load on the write instance of RDS.
=> feat: move DB write actions to submission server

Makefile, pkg/app/app.go
Remove the QR code servlets from the key submission and retrieval servers.
Also removes the QR code tests from the `make test` command.
=> chore: remove QR code servlets
